Repository apollographql/docs, pull requests merged in 2023-12, with the labels that each got.

#495 Configure Renovate
  .github/renovate.json5
Labels: dependencies

#664 chore(deps): update dependency @braintree/sanitize-url to 6.0.1 [security]
  package-lock.json
  package.json
Labels: dependencies, vulnerability

#666 chore(deps): update dependency gatsby to v4.25.7 [security]
  package-lock.json
  package.json
Labels: dependencies, vulnerability

#663 Update TN0039-debugging-subgraph-requests
  src/content/technotes/TN0039-debugging-subgraph-requests.mdx
Labels: technote
